### ISSUE TITLE
[FEATURE] Create an enum for Resources

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#173]
### Is your feature request related to a problem?

To support the deprovisioning workflow we need a consistent set of Strings associated with resource types (e.g. `connector_id`).

Currently many of these are constant strings in the `common` package which is a good first step.  Some of them are hardcoded in the workflow steps which is not a good practice.

### What solution would you like?

Create an enum associated with Resources created where the enum name can be used (lowercased) for the JSON string key.

**Comment by amitgalitz** [comment]
Adding to this issue that we should have more consistent step names as well. for example for  `/_plugins/_ml/model_groups/_register` we just have `model_group`  but for `/_plugins/_ml/models/_register` we have `register_remote_model` and etc. 

registerRemoteModel and registerLocalModel are a little more unique and there are also edge cases like like `create_index` where that name isn't anywhere in api path since its just `PUT <index_name>`

**Comment by dbwiddis** [comment]
Fixed in #231
